import type { CharacterConfig } from './types';
import {
  ExplorerGirl,
  DreamerGirl,
  GardenerGirl,
  ArtistGirl,
  SageGirl,
  AdventurerGirl,
  MusicianGirl,
  StargazerGirl,
  TechieGirl,
  JoyGirl,
} from './characters';

export const CHARACTERS: CharacterConfig[] = [
  {
    id: 'explorer',
    name: 'المستكشفة',
    description: 'تحبين اكتشاف كل زاوية في الجزيرة. حقيبتك دائماً مليئة بالأدوات والخرائط.',
    personality: 'explorer',
    colors: {
      primary: '#5A7A3A',
      secondary: '#8B6914',
      accent: '#C49A3C',
      bg: 'rgba(90,122,58,0.15)',
    },
    appearance: {
      hairColor: '#8B6914',
      outfitColor: '#5A7A3A',
      accentColor: '#C49A3C',
      skinTone: '#F5D6C6',
    },
    animationType: 'float',
    component: ExplorerGirl,
  },
  {
    id: 'dreamer',
    name: 'الحالمة',
    description: 'ترين الجمال في تفاصيل الجزيرة المخفية. عيناكِ تراقبان النجوم كل ليلة.',
    personality: 'dreamer',
    colors: {
      primary: '#6B5B9B',
      secondary: '#9B6B9B',
      accent: '#E8D0FF',
      bg: 'rgba(107,91,155,0.15)',
    },
    appearance: {
      hairColor: '#9B6B9B',
      outfitColor: '#6B5B9B',
      accentColor: '#E8D0FF',
      skinTone: '#F0E0D0',
    },
    animationType: 'glow',
    component: DreamerGirl,
  },
  {
    id: 'gardener',
    name: 'البستانية',
    description: 'الأزهار تتفتح حيث تمرين. تعرفين أسرار النباتات وتحبين الاعتناء بالجزيرة.',
    personality: 'explorer',
    colors: {
      primary: '#6B8E23',
      secondary: '#A0522D',
      accent: '#FFB7C5',
      bg: 'rgba(107,142,35,0.15)',
    },
    appearance: {
      hairColor: '#A0522D',
      outfitColor: '#6B8E23',
      accentColor: '#FFB7C5',
      skinTone: '#F5D6C6',
    },
    animationType: 'gentle',
    component: GardenerGirl,
  },
  {
    id: 'artist',
    name: 'الفنانة',
    description: 'تحملين فرشاة وقصة. كل منظر في الجزيرة لوحة تنتظر أن ترسميها.',
    personality: 'funny',
    colors: {
      primary: '#FF6347',
      secondary: '#FFD700',
      accent: '#FF69B4',
      bg: 'rgba(255,99,71,0.12)',
    },
    appearance: {
      hairColor: '#8B4513',
      outfitColor: '#FF6347',
      accentColor: '#FFD700',
      skinTone: '#F5D6C6',
    },
    animationType: 'bounce',
    component: ArtistGirl,
  },
  {
    id: 'ocean',
    name: 'ابنة البحر',
    description: 'الأمواج تناديكِ. تعرفين أسرار المحيط وتحبين الاستماع إلى همس البحر.',
    personality: 'dreamer',
    colors: {
      primary: '#191970',
      secondary: '#2A2A8A',
      accent: '#FFD700',
      bg: 'rgba(25,25,112,0.15)',
    },
    appearance: {
      hairColor: '#2A2A5A',
      outfitColor: '#191970',
      accentColor: '#FFD700',
      skinTone: '#E8D8C8',
    },
    animationType: 'drift',
    component: StargazerGirl,
  },
  {
    id: 'storykeeper',
    name: 'حارسة الحكايات',
    description: 'تحملين كتاباً قديماً مليئاً بأسرار الجزيرة. كل قصة تنتظر من يرويها.',
    personality: 'dreamer',
    colors: {
      primary: '#4A6FA5',
      secondary: '#D3D3D3',
      accent: '#C49A3C',
      bg: 'rgba(74,111,165,0.15)',
    },
    appearance: {
      hairColor: '#D3D3D3',
      outfitColor: '#4A6FA5',
      accentColor: '#C49A3C',
      skinTone: '#E8E0D0',
    },
    animationType: 'glow',
    component: SageGirl,
  },
  {
    id: 'builder',
    name: 'المهندسة',
    description: 'تبنين أحلامكِ بيديكِ. كل بناء في الجزيرة يحمل لمسة إبداعكِ.',
    personality: 'explorer',
    colors: {
      primary: '#3A7A7A',
      secondary: '#2A5A5A',
      accent: '#00CED1',
      bg: 'rgba(58,122,122,0.15)',
    },
    appearance: {
      hairColor: '#3A7A7A',
      outfitColor: '#3A7A7A',
      accentColor: '#00CED1',
      skinTone: '#F0D8C8',
    },
    animationType: 'bounce',
    component: TechieGirl,
  },
  {
    id: 'musician',
    name: 'الموسيقية',
    description: 'أنغامكِ تجعل أزهار الجزيرة تتفتح. الموسيقى هي لغتكِ مع العالم.',
    personality: 'funny',
    colors: {
      primary: '#9370DB',
      secondary: '#800020',
      accent: '#FFD700',
      bg: 'rgba(147,112,219,0.15)',
    },
    appearance: {
      hairColor: '#800020',
      outfitColor: '#9370DB',
      accentColor: '#FFD700',
      skinTone: '#F0E0D0',
    },
    animationType: 'float',
    component: MusicianGirl,
  },
  {
    id: 'adventurer',
    name: 'المغامرة',
    description: 'لا تخافين من المجهول. أنتِ أول من يخوض المغامرات في أعماق الجزيرة.',
    personality: 'explorer',
    colors: {
      primary: '#B22222',
      secondary: '#DAA520',
      accent: '#8B0000',
      bg: 'rgba(178,34,34,0.12)',
    },
    appearance: {
      hairColor: '#8B0000',
      outfitColor: '#B22222',
      accentColor: '#DAA520',
      skinTone: '#EDD0C0',
    },
    animationType: 'float',
    component: AdventurerGirl,
  },
  {
    id: 'joy',
    name: 'البهجة',
    description: 'الضحكة التي تنور أي مكان. مرحكِ يجعل رحلة الجزيرة أجمل للجميع.',
    personality: 'funny',
    colors: {
      primary: '#FF69B4',
      secondary: '#FFD700',
      accent: '#87CEEB',
      bg: 'rgba(255,105,180,0.15)',
    },
    appearance: {
      hairColor: '#FF6347',
      outfitColor: '#FF69B4',
      accentColor: '#FFD700',
      skinTone: '#F5D6C6',
    },
    animationType: 'bounce',
    component: JoyGirl,
  },
];

export const CHARACTER_MAP = Object.fromEntries(CHARACTERS.map((c) => [c.id, c]));
